# Generated by Django 3.0.8 on 2020-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('date', models.DateField(auto_now=True, verbose_name='дата создания')),
            ],
        ),
    ]
