# Generated by Django 3.0.8 on 2020-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_auto_20200716_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(auto_created=True, verbose_name='дата создания'),
        ),
    ]
