# Generated by Django 3.0.8 on 2020-07-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20200716_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, max_length=32, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.CharField(blank=True, max_length=32, verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('e', 'Для новичков'), ('n', 'Не придумал для кого'), ('h', 'Для старичков')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=5, verbose_name='цена'),
        ),
    ]
