# Generated by Django 3.0.8 on 2020-07-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_auto_20200716_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=999, verbose_name='цена'),
        ),
    ]
